$('[data-logout]').onclick=logout;
$$('[data-nav]').forEach(b=>b.onclick=()=>{const id=b.dataset.nav;if(id==='today'){view='today';modal=null;render()}else if(id==='calendar')openModal('calendar');else if(id==='students')openModal('students');else if(id==='schedule')openModal('schedule');else if(id==='payments')openModal('payments',{filter:'all'});else if(id==='homework')openModal('homework');else if(id==='materials')openModal('materials')});
$$('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));
$$('[data-chime]').forEach(b=>b.onclick=()=>{playChime();b.animate([{transform:'scale(1)'},{transform:'scale(1.2) rotate(9deg)'},{transform:'scale(1)'}],{duration:320})});
const close=$('[data-close]');if(close)close.onclick=()=>{modal=null;render()};const backdrop=$('.modal-backdrop');if(backdrop)backdrop.onclick=e=>{if(e.target===backdrop){modal=null;render()}};
const mediaLink=$('[data-media-link]');if(mediaLink)mediaLink.onclick=()=>{state.mediaUrl=$('#mediaUrl').value.trim();if(mediaRuntime.url){URL.revokeObjectURL(mediaRuntime.url);mediaRuntime={url:'',type:'',name:''}}save();render()};const mf=$('#mediaFile');if(mf)mf.onchange=()=>{const f=mf.files[0];if(!f)return;if(mediaRuntime.url)URL.revokeObjectURL(mediaRuntime.url);mediaRuntime={url:URL.createObjectURL(f),type:f.type||inferType(f.name),name:f.name};showToast(`Открыт файл: ${f.name}`);render()};const full=$('[data-media-full]');if(full)full.onclick=()=>{const box=$('#mediaBox');if(document.fullscreenElement)document.exitFullscreen();else box?.requestFullscreen?.()};
const addTask=$('[data-add-task]');if(addTask)addTask.onclick=()=>{syncPlanFromDom();const key=dateKey();state.plans[key]=state.plans[key]||[];state.plans[key].push({done:false,time:'09:00',task:''});save();render()};$$('[data-plan-row]').forEach((r,i)=>{r.addEventListener('input',e=>{if(e.target.matches('[data-plan-task]'))syncPlanFromDom()});r.addEventListener('change',e=>{if(e.target.matches('[data-plan-done],[data-plan-time]')){syncPlanFromDom();if(e.target.matches('[data-plan-done]'))render()}});$('[data-plan-del]',r).onclick=()=>{syncPlanFromDom();state.plans[dateKey()].splice(i,1);persist('Дело удалено')}});
$$('[data-pay-filter]').forEach(b=>b.onclick=()=>openModal('payments',{filter:b.dataset.payFilter}));
$$('[data-year]').forEach(b=>b.onclick=()=>{modal.year=+b.dataset.year;render()});const yb=$('[data-year-back]');if(yb)yb.onclick=()=>{delete modal.year;render()};
const addClass=$('[data-add-class]');if(addClass)addClass.onclick=()=>{state.students.push({className:'Новый класс',students:[]});persist('Класс добавлен')};$$('[data-add-student]').forEach((b,ci)=>b.onclick=()=>{state.students[ci].students.push({name:'',grade:''});persist('Ученик добавлен')});$$('[data-student-del]').forEach(b=>b.onclick=()=>{const c=+b.closest('[data-class]').dataset.class,s=+b.closest('[data-student]').dataset.student;state.students[c].students.splice(s,1);persist('Ученик удалён')});$$('[data-save-students]').forEach(b=>b.onclick=()=>{$$('[data-class]').forEach((c,ci)=>{$$('[data-student]',c).forEach((r,si)=>{state.students[ci].students[si].name=$('[data-student-name]',r).value;state.students[ci].students[si].grade=$('[data-student-grade]',r).value})});persist('Списки сохранены')});
const schAdd=$('[data-schedule-add]');if(schAdd)schAdd.onclick=()=>{syncScheduleFromDom();state.schedule.push({id:uid(),dow:1,time:'09:00',name:'Новый урок',group:'',color:'lilac'});save();render()};$$('[data-schedule]').forEach(r=>{r.addEventListener('input',e=>{if(e.target.matches('[data-sch-name],[data-sch-group]'))syncScheduleFromDom()});r.addEventListener('change',e=>{if(e.target.matches('[data-sch-dow],[data-sch-time],[data-sch-color]'))syncScheduleFromDom()})});$$('[data-sch-del]').forEach((b,i)=>b.onclick=()=>{syncScheduleFromDom();state.schedule.splice(i,1);persist('Урок удалён')});const schSave=$('[data-schedule-save]');if(schSave)schSave.onclick=()=>{syncScheduleFromDom();showToast('Расписание сохранено');render()};
const newSave=$('[data-new-save]');if(newSave)newSave.onclick=()=>{state.schedule.push({id:uid(),dow:+$('#newDow').value,time:$('#newTime').value,name:$('#newName').value.trim()||'Новый урок',group:$('#newGroup').value.trim(),color:$('#newColor').value});save();modal=null;showToast('Урок добавлен');render()};
const pa=$('[data-payment-add]');if(pa)pa.onclick=()=>{state.payments.push({id:uid(),childName:'',className:'',parentName:'',phone:'',dueDate:dateKey(),paid:false});save();modal.filter='all';render()};$$('[data-payment-view]').forEach(b=>b.onclick=()=>{modal.filter=b.dataset.paymentView;render()});$$('[data-payment]').forEach(r=>{r.addEventListener('input',e=>{if(e.target.matches('input:not([type=checkbox]):not([type=date])'))syncPaymentRow(r)});r.addEventListener('change',e=>{if(e.target.matches('[data-pay-due],[data-pay-paid]')){syncPaymentRow(r);render()}});$('[data-pay-del]',r).onclick=()=>{state.payments=state.payments.filter(x=>x.id!==r.dataset.payment);persist('Запись удалена')}});
const hw=$('[data-hw-save]');if(hw)hw.onclick=()=>{const d=$('#hwDate').value,t=$('#hwText').value.trim(),f=$('#hwFile').files[0]?.name||'';if(!d||!t)return showToast('Укажите дату и задание');state.homework.unshift({id:uid(),date:d,text:t,file:f});persist('Домашнее задание сохранено')};const ms=$('[data-mat-save]');if(ms)ms.onclick=()=>{const n=$('#matName').value.trim(),f=$('#matFile').files[0]?.name||'';if(!n)return showToast('Введите название материала');state.materials.push({id:uid(),name:n,file:f||'файл не выбран'});persist('Материал добавлен')};$$('[data-mat-del]').forEach(b=>b.onclick=()=>{state.materials.splice(+b.dataset.matDel,1);persist('Материал удалён')});const is=$('[data-idea-save]');if(is)is.onclick=()=>{const v=$('#ideaText').value.trim();if(!v)return;state.ideas.unshift(v);persist('Идея сохранена')};$$('[data-idea-edit]').forEach(b=>b.onclick=()=>{const i=+b.dataset.ideaEdit,n=prompt('Изменить идею:',state.ideas[i]);if(n!==null){state.ideas[i]=n;persist('Идея обновлена')}})
}
function playChime(){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),now=ctx.currentTime;[880,1320,1760].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(f,now+i*.055);g.gain.setValueAtTime(0,now+i*.055);g.gain.linearRampToValueAtTime(.09/(i+1),now+i*.065);g.gain.exponentialRampToValueAtTime(.0001,now+.48+i*.05);o.connect(g).connect(ctx.destination);o.start(now+i*.055);o.stop(now+.55+i*.05)});setTimeout(()=>ctx.close(),800)}catch{}}
function updateClock(){const el=$('#clockTime'),d=$('#clockDate');if(!el)return;const parts=new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date()),v=Object.fromEntries(parts.map(p=>[p.type,p.value]));el.textContent=`${v.hour}:${v.minute}:${v.second}`;const today=currentDate(),key=dateKey(today);if(d)d.textContent=fmtTop(today);if(lastCalendarDateKey&&lastCalendarDateKey!==key){lastCalendarDateKey=key;render();return}lastCalendarDateKey=key}
setInterval(updateClock,1000);restoreSession();render();
